// <auto-generated />
namespace Mentira.Crud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class sistemasClases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sistemasClases));
        
        string IMigrationMetadata.Id
        {
            get { return "201908060707550_sistemasClases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
